<template>
  <div class="audio-page mb-5">
    <div class="shadow-sm p-5 bg-white rounded">
      <header class="text-center border-bottom border-warning mb-4">
        <h1 class="text-dark">MediaStream Recording API</h1>
        <h3>aka Media Recorder API</h3>
      </header>
      <p class="lead">
        The MediaStream Recording API makes it possible to capture the data (audio & video) generated by a MediaStream or HTMLMediaElement object for analysis, processing or saving to disk.
      </p>
    </div>
  </div>
</template>

<script>
export default {
  data () {
    return {
      key: 'value'
    }
  }
}
</script>

<style scoped>

</style>
